# Generated by Django 3.0.5 on 2020-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
