# Generated by Django 3.0.5 on 2020-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200522_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
