# Generated by Django 3.0.5 on 2020-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200523_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cityPreference',
            field=models.CharField(choices=[('BGL', 'Bangalore'), ('DEL', 'Delhi'), ('BOM', 'Mumbai'), ('NE', 'North-East')], max_length=30),
        ),
    ]
