# Generated by Django 3.0.5 on 2020-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200523_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cityPreference',
            field=models.CharField(choices=[('BGL', 'Bangalore'), ('DEL', 'Delhi'), ('BOM', 'Mumbai'), ('NE', 'North-East'), ('CHD', 'Chandigarh'), ('PJB', 'Punjab'), ('AMD', 'Ahemdabad'), ('OT', 'Others')], max_length=30),
        ),
    ]
